services:
  db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: mediawiki
      MARIADB_USER: wiki
      MARIADB_PASSWORD: example
      MARIADB_ROOT_PASSWORD: rootpass
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uwiki", "-pexample"]
      interval: 5s
      retries: 5

  wiki:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      MW_SITE_SERVER: http://localhost:8080
      MW_SCRIPT_PATH: ""
      MW_SITE_NAME: "Giant Bomb Wiki"
      MW_DB_HOST: db
      MW_DB_NAME: mediawiki
      MW_DB_USER: wiki
      MW_DB_PASSWORD: example
    volumes:
      #Extensions
      - ./extensions:/var/www/html/extensions:cached
      #These lines cause these extensions not to be mounted to volume
      - /var/www/html/extensions/SemanticMediaWiki
      - /var/www/html/extensions/SemanticExtraSpecialProperties
      - /var/www/html/extensions/SemanticResultFormats
      - /var/www/html/extensions/SemanticScribunto
      - /var/www/html/extensions/CodeEditor
      - /var/www/html/extensions/WikiEditor
      - /var/www/html/extensions/Scribunto
      - /var/www/html/extensions/TemplateData
      - /var/www/html/extensions/TemplateStyles
      - /var/www/html/extensions/TemplateStylesExtender
      #Skins
      - ./skins:/var/www/html/skins:cached
      #These lines cause these skins not to be mounted to volume
      - /var/www/html/skins/Vector

      - ./config:/config
      - wiki-data:/var/www/html/images
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/entrypoint.sh"]

volumes:
  db-data:
  wiki-data: {}
