services:
  db:
    image: mariadb:11
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: "mariadb -uroot -p$MARIADB_ROOT_PASSWORD $MARIADB_DATABASE -e 'SHOW DATABASES;'"
      interval: 5s
      retries: 5

  wiki:
    build: .
    privileged: true
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      #Use gscfuse to mount images
      - /dev/fuse:/dev/fuse
      - ./gcs_key.json:/etc/gcloud/service-account.json
      - ./mountpoint:/var/www/html/images
      #Skins
      - ./skins:/var/www/html/skins:cached
      #These lines cause these skins not to be mounted to volume
      - /var/www/html/skins/Vector

      - ./config:/config
      - ./data:/data/
      - ./entrypoint.sh:/entrypoint.sh:ro
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/etc/gcloud/service-account.json
    entrypoint: ["/entrypoint.sh"]

volumes:
  db-data:
  