services:
  db:
    image: mariadb:11
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
<<<<<<< Updated upstream
=======
      - ./wiki_schema.sql:/docker-entrypoint-initdb.d/wiki_schema.sql:ro
>>>>>>> Stashed changes
    healthcheck:
      test: "mariadb -uroot -p$MARIADB_ROOT_PASSWORD $MARIADB_DATABASE -e 'SHOW DATABASES;'"
      interval: 5s
      retries: 5

  wiki:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      #Skins
      - ./skins:/var/www/html/skins:cached
      #These lines cause these skins not to be mounted to volume
      - /var/www/html/skins/Vector

      - ./config:/config
      - wiki-data:/var/www/html/images
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/entrypoint.sh"]

volumes:
  db-data:
  wiki-data: {}
