services:
  db:
    image: mariadb:11
    command: --skip-name-resolve=0
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: "mariadb -uroot -p$MARIADB_ROOT_PASSWORD $MARIADB_DATABASE -e 'SHOW DATABASES;'"
      interval: 5s
      retries: 5

  wiki:
    build:
      context: .
      args:
        INSTALL_API: "false"
        INSTALL_GCSFUSE: "false"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      #Skins
      - ./skins:/var/www/html/skins:cached
      #These lines cause these skins not to be mounted to volume
      - /var/www/html/skins/Vector

      - ./config:/config
      - ./data:/data/
      - wiki-data:/var/www/html/images
      - ./entrypoint.sh:/entrypoint.sh:ro
    environment:
      - MV_ENV=dev
    entrypoint: ["/entrypoint.sh"]

volumes:
  db-data:
  wiki-data: {}
