name: Test Mediawiki Version Page End-to-End
on: [workflow_dispatch, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Create the .env file the installation will require
        run: |
          echo "MARIADB_DATABASE: gb_wiki_ci" >> .env
          echo "MARIADB_API_DUMP_DATABASE=gb_api_dump" >> .env
          echo "MARIADB_USER=wiki_admin_ci" >> .env
          echo "MARIADB_PASSWORD=test.password.ci" >> .env
          echo "MARIADB_ROOT_PASSWORD: gb_root_ci" >> .env
          echo "MW_SITE_SERVER=http://localhost:8080" >> .env
          echo "MW_SCRIPT_PATH=\"\"" >> .env
          echo "MW_SITE_NAME=\"Giant Bomb Wiki\"" >> .env
          echo "MW_DB_HOST=db" >> .env
          echo "MW_DB_NAME=gb_wiki_ci" >> .env
          echo "MW_DB_USER=giantbomb.ci" >> .env
          echo "MW_PASS=gbwikipass.ci" >> .env
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1.2
      - name: Install pnpm explicitly
        uses: pnpm/action-setup@v4
      - name: Start every service, install the wiki, and upload logs
        run: |
          docker compose up --build -d
          docker exec giant-bomb-wiki-wiki-1 /bin/bash /installwiki.sh
          docker compose logs --tail=50 > logs.txt
      - name: Upload docker logs
        uses: actions/upload-artifact@v4
        with:
          name: container-logs
          path: logs.txt
      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: "http://localhost:8080"
          wait-on-timeout: 180 # seconds
          browser: chrome
          with: cypress/e2e/special_version.cy.ts
